version: '3.9'
services:
  postgres:
    image: postgres:16.1-alpine
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=$DB_USERNAME
      - POSTGRES_PASSWORD=$DB_PASSWORD
      - POSTGRES_DB=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - db_network

  app:
    image: backend-server
    env_file:
      - .env
    environment:
      - POSTGRES_URL=$POSTGRES_URL
    command: pnpm start
    ports:
      - $PORT:$PORT
    depends_on:
      - postgres
    networks:
      - db_network
volumes:
  postgres_data:
networks:
  db_network:
